package com.example.taptoplay.ui

import android.content.Context
import androidx.compose.runtime.compositionLocalOf
import com.example.taptoplay.catalog.Product
import com.example.taptoplay.profiles.PaymentEnvironment
import java.util.Locale

internal enum class AppLanguage(val tag: String, val nativeName: String) {
    English("en", "English"),
    Spanish("es", "Español"),
    Dutch("nl", "Nederlands");

    companion object {
        fun fromTag(tag: String?): AppLanguage =
            entries.firstOrNull { it.tag == tag } ?: English
    }
}

internal class AppLanguageStore(context: Context) {
    private val prefs = context.getSharedPreferences("tap_to_play_language", Context.MODE_PRIVATE)

    fun selected(): AppLanguage =
        AppLanguage.fromTag(prefs.getString(KEY_LANGUAGE, AppLanguage.English.tag))

    fun save(language: AppLanguage) {
        prefs.edit().putString(KEY_LANGUAGE, language.tag).apply()
    }

    private companion object {
        const val KEY_LANGUAGE = "language"
    }
}

internal val LocalTapToPlayStrings = compositionLocalOf { stringsFor(AppLanguage.English) }

internal data class TapToPlayStrings(
    val language: AppLanguage,
    val values: Map<String, String>,
    private val productNames: Map<String, String>,
    private val productDescriptions: Map<String, String>,
    private val categories: Map<String, String>,
) {
    val locale: Locale = Locale.forLanguageTag(language.tag)

    operator fun get(key: String): String =
        values.getValue(key)

    fun format(key: String, vararg args: Any): String =
        String.format(locale, values.getValue(key), *args)

    fun screenLabel(screen: AppScreen): String = when (screen) {
        AppScreen.Catalog -> this["screen_catalog"]
        AppScreen.Checkout -> this["screen_checkout"]
        AppScreen.PaymentsApp -> this["screen_payments_app"]
        AppScreen.Transactions -> this["screen_transactions"]
        AppScreen.Diagnostics -> this["screen_diagnostics"]
        AppScreen.Language -> this["screen_language"]
        AppScreen.About -> this["screen_about"]
    }

    fun productName(product: Product): String =
        productNames[product.id] ?: product.name

    fun productDescription(product: Product): String =
        productDescriptions[product.id] ?: product.description

    fun categoryLabel(category: String): String =
        categories[category] ?: category

    fun environmentLabel(environment: PaymentEnvironment): String = when (environment) {
        PaymentEnvironment.TEST -> this["environment_test"]
        PaymentEnvironment.LIVE -> this["environment_live"]
    }

    fun itemsReady(count: Int): String =
        if (count == 1) this["cart_item_ready_one"] else format("cart_item_ready_many", count)

    fun itemCount(count: Int): String =
        if (count == 1) this["item_count_one"] else format("item_count_many", count)

    fun jsonFieldCount(count: Int): String =
        if (count == 1) this["json_field_count_one"] else format("json_field_count_many", count)

    fun savedPaymentAttempts(count: Int): String =
        if (count == 1) this["saved_attempt_one"] else format("saved_attempt_many", count)

    fun loadedPaymentInstances(count: Int): String =
        if (count == 1) this["loaded_instance_one"] else format("loaded_instance_many", count)

    fun saleToAcquirerDataSummary(name: String, count: Int): String =
        format("sale_to_acquirer_data_summary", name, jsonFieldCount(count))

    fun chargingProfile(profileName: String, environment: PaymentEnvironment): String =
        format("charging_profile", profileName, environmentLabel(environment))

    fun languageChanged(language: AppLanguage): String =
        format("status_language_changed", language.nativeName)

    fun secretMask(value: String): String = when {
        value.isBlank() -> this["not_set"]
        value.length <= 8 -> "****"
        else -> value.take(4) + "..." + value.takeLast(4)
    }

    fun passphraseMask(value: String): String =
        if (value.isBlank()) this["not_set"] else this["secret_set_hidden"]

    fun maskedIdentifier(value: String?): String = when {
        value.isNullOrBlank() -> this["not_set"]
        value.length <= 8 -> "****"
        else -> value.take(4) + "..." + value.takeLast(4)
    }
}

internal fun stringsFor(language: AppLanguage): TapToPlayStrings = when (language) {
    AppLanguage.English -> englishStrings
    AppLanguage.Spanish -> spanishStrings
    AppLanguage.Dutch -> dutchStrings
}

internal fun allLocalizedStringSets(): List<TapToPlayStrings> =
    AppLanguage.entries.map(::stringsFor)

private val englishStrings = TapToPlayStrings(
    language = AppLanguage.English,
    values = mapOf(
        "app_name" to "TapToPlay",
        "app_subtitle" to "Payments App Made Easy",
        "screen_catalog" to "Catalog",
        "screen_checkout" to "Checkout",
        "screen_payments_app" to "Payments App",
        "screen_transactions" to "Transactions",
        "screen_diagnostics" to "Diagnostics",
        "screen_language" to "Language",
        "screen_about" to "About",
        "menu" to "Menu",
        "open_menu" to "Open menu",
        "scroll_to_cart" to "Scroll to cart",
        "latest_action" to "Latest action",
        "cart" to "Cart",
        "cart_empty_hint" to "Add garments to build a checkout.",
        "cart_item_ready_one" to "1 item ready",
        "cart_item_ready_many" to "%d items ready",
        "go_to_checkout" to "Go to checkout",
        "no_payment_profile_selected" to "No payment profile selected",
        "charging_profile" to "Charging profile: %s (%s)",
        "added" to "Added",
        "add_to_cart" to "Add to cart",
        "checkout_empty_hint" to "Add garments to start a Tap to Pay checkout.",
        "clear" to "Clear",
        "total" to "Total",
        "reset" to "Reset",
        "scan_data_qr" to "Scan data QR",
        "view" to "View",
        "hide" to "Hide",
        "save" to "Save",
        "apply" to "Apply",
        "close" to "Close",
        "favorites" to "Favorites",
        "use" to "Use",
        "remove" to "Remove",
        "json_field_count_one" to "1 JSON field",
        "json_field_count_many" to "%d JSON fields",
        "sale_to_acquirer_data_summary" to "%s | %s",
        "charge_live_payment" to "Charge live payment",
        "charge_test_payment" to "Charge test payment",
        "payments_app_not_boarded" to "Payment App not boarded",
        "payments_app_not_boarded_body" to "Open Payments App status to check boarding, get a request token, or finish setup before charging.",
        "open_payments_app_status" to "Open Payments App status",
        "confirm_live_payment" to "Confirm live payment",
        "confirm_live_payment_body" to "This will launch a live Adyen Tap to Pay charge.",
        "charge_live" to "Charge live",
        "cancel" to "Cancel",
        "amount" to "Amount",
        "items" to "Items",
        "profile" to "Profile",
        "environment" to "Environment",
        "merchant" to "Merchant",
        "store_name" to "Store name",
        "store" to "Store",
        "store_id" to "Store ID",
        "environment_test" to "test",
        "environment_live" to "live",
        "payment_profile" to "Payment profile",
        "boarding_no_profile" to "No profile",
        "boarding_boarded" to "Boarded",
        "boarding_ready_to_board" to "Ready to board",
        "boarding_collapsed_setup" to "Collapsed setup",
        "setup" to "Setup",
        "scan_qr" to "Scan QR",
        "no_credential_profile_loaded" to "No credential profile loaded",
        "credential_profile_empty_body" to "Create a credential QR from the TapToPlay schema before boarding the Adyen Payments app.",
        "open_qr_documentation" to "Open QR documentation",
        "secure_device_vault" to "Secure device vault",
        "secure_device_vault_body" to "Scanned QR profiles are stored with Android encrypted preferences. Secrets stay masked in the app.",
        "api_key" to "API key",
        "terminal_key" to "Terminal key",
        "passphrase" to "Passphrase",
        "installation" to "Installation",
        "boarding_request_token" to "Boarding request token",
        "boarding_token" to "Boarding token",
        "installation_not_returned_yet" to "not returned yet",
        "boarding_token_exchanged" to "exchanged for boarding token",
        "boarding_token_received" to "received from check",
        "boarding_token_not_needed" to "not needed after boarding",
        "boarding_token_not_received" to "not received",
        "boarding_token_generated" to "generated for latest board link",
        "boarding_token_not_generated" to "not generated yet",
        "boarding_token_not_requested" to "not requested",
        "check" to "Check",
        "board" to "Board",
        "reboard" to "Reboard",
        "remove_payment_profile_title" to "Remove payment profile?",
        "remove_payment_profile_body" to "This removes %s from the local encrypted vault and clears its saved boarding state. Adyen app authentication is not revoked unless you revoke the instance separately.",
        "payments_app_not_installed" to "Payments app not installed",
        "payments_app_not_installed_body" to "Install the %s Adyen Payments app from Google Play, then return here and run Check again.",
        "open_google_play" to "Open Google Play",
        "payments_app_instances" to "Payments App instances",
        "payments_app_status_boarding" to "boarding",
        "payments_app_status_boarded" to "boarded",
        "payments_app_status_revoked" to "revoked",
        "payments_app_status_unknown" to "unknown",
        "refresh" to "Refresh",
        "hide_revoked" to "Hide revoked",
        "show_revoked" to "Show revoked",
        "instances_no_profile" to "Scan or select an Adyen profile to inspect app instances.",
        "instances_empty" to "No instances loaded yet. Refresh uses the scanned profile API key.",
        "instances_only_revoked_hidden" to "Only revoked instances are hidden. Show revoked to inspect them.",
        "current" to "Current",
        "no_merchant_store_returned" to "No merchant/store returned",
        "revoke_instance" to "Revoke instance",
        "revoke" to "Revoke",
        "revoke_instance_title" to "Revoke Payments App instance?",
        "revoke_instance_body" to "This revokes installation %s through Adyen. Payments on that app/device need reboarding afterward.",
        "edit" to "Edit",
        "value" to "Value",
        "remove_group" to "Remove group",
        "field_count_one" to "1 field",
        "field_count_many" to "%d fields",
        "array_item_count_one" to "1 item",
        "array_item_count_many" to "%d items",
        "transactions_empty_title" to "No payment attempts yet",
        "saved_attempt_one" to "1 saved payment attempt",
        "saved_attempt_many" to "%d saved payment attempts",
        "transactions_empty_body" to "Each checkout attempt will appear here with its Terminal API request and Adyen response.",
        "inspect" to "Inspect",
        "adyen_issue" to "Adyen issue: %s",
        "transaction_status_pending" to "Pending",
        "transaction_status_approved" to "Approved",
        "transaction_status_refused" to "Refused",
        "transaction_status_failed" to "Failed",
        "transaction_status_refunding" to "Refunding",
        "transaction_status_refunded" to "Refunded",
        "boarding_returned" to "Boarding returned",
        "refund_approved" to "Refund approved",
        "payment_approved" to "Payment approved",
        "payment_refused" to "Payment refused",
        "adyen_result" to "Adyen result",
        "done" to "Done",
        "adyen_app_is_state" to "Adyen app is %s. Installation ID: %s",
        "boarded" to "boarded",
        "not_boarded" to "not boarded",
        "not_supplied" to "not supplied",
        "previous_merchant" to "Previous merchant: %s",
        "previous_store" to "Previous store: %s",
        "reboarding_flow_started" to "Reboarding flow started",
        "reference" to "Reference: %s",
        "no_refusal_reason" to "No refusal reason supplied.",
        "transaction" to "Transaction",
        "refund" to "Refund",
        "request" to "Request",
        "response" to "Response",
        "receipt" to "Receipt",
        "terminal_api_request" to "Terminal API request",
        "raw_terminal_api_request" to "Raw Terminal API request",
        "show_raw_json" to "Show raw JSON",
        "hide_raw_json" to "Hide raw JSON",
        "json_parse_failed" to "JSON could not be parsed.",
        "important_response_fields" to "Important response fields",
        "adyen_failure_detail" to "Adyen failure detail",
        "adyen_response" to "Adyen response",
        "no_response_received" to "No response has been received yet.",
        "raw_terminal_api_response" to "Raw Terminal API response",
        "raw_return_uri" to "Raw return URI",
        "no_receipt_data" to "No PaymentReceipt data was returned for this transaction.",
        "adyen_generated_receipt_data" to "Adyen-generated receipt data",
        "signature" to "Signature",
        "receipt_status_voided" to "Voided",
        "merchant_receipt" to "Merchant receipt",
        "customer_receipt" to "Customer receipt",
        "receipt_type" to "Type",
        "receipt_payment_method" to "Payment method",
        "receipt_card" to "Card",
        "receipt_card_number" to "Card number",
        "receipt_authorisation" to "Authorisation",
        "receipt_date" to "Date",
        "receipt_time" to "Time",
        "receipt_transaction_reference" to "Transaction reference",
        "receipt_terminal" to "Terminal",
        "receipt_merchant_id" to "Merchant ID",
        "receipt_original_amount" to "Original amount",
        "receipt_shopper_amount" to "Shopper amount",
        "receipt_tip_amount" to "Tip",
        "receipt_surcharge" to "Surcharge",
        "receipt_cashback_amount" to "Cashback",
        "receipt_charity_amount" to "Charity",
        "receipt_discount_amount" to "Discount",
        "receipt_payment_method_variant" to "Payment method variant",
        "receipt_funding_source" to "Funding source",
        "receipt_product_type" to "Product type",
        "receipt_pos_entry_mode" to "Entry mode",
        "receipt_application" to "Application",
        "receipt_expiry_date" to "Expiry date",
        "receipt_cardholder_name" to "Cardholder",
        "receipt_account_type" to "Account type",
        "receipt_authorization_type" to "Authorization type",
        "receipt_authorization_response" to "Authorization response",
        "receipt_cvm_result" to "CVM result",
        "receipt_additional_emv_data" to "Additional EMV data",
        "receipt_pan_sequence" to "PAN sequence",
        "receipt_current_balance" to "Current balance",
        "receipt_dcc_explanation" to "DCC explanation",
        "receipt_dcc_markup" to "DCC markup",
        "receipt_dcc_rate" to "DCC rate",
        "receipt_dcc_shopper_amount" to "DCC shopper amount",
        "receipt_dcc_source" to "DCC source",
        "receipt_wallet_dcc_amount" to "Wallet DCC amount",
        "receipt_wallet_dcc_rate" to "Wallet DCC rate",
        "receipt_wallet_operation" to "Wallet operation",
        "receipt_wallet_reference" to "Wallet reference",
        "receipt_token_variant" to "Token variant",
        "receipt_buyer_id" to "Buyer ID",
        "receipt_qr_code" to "QR code",
        "request_summary" to "Request summary",
        "message_category" to "Message category",
        "service_id" to "ServiceID",
        "sale_transaction" to "Sale transaction",
        "adyen_transaction" to "Adyen transaction",
        "refund_of" to "Refund of",
        "decoded_sale_to_acquirer_data" to "Decoded SaleToAcquirerData",
        "no_sale_to_acquirer_data" to "This request does not include PaymentRequest.SaleData.SaleToAcquirerData.",
        "raw_sale_to_acquirer_data" to "Raw JSON sent inside PaymentRequest.SaleData.SaleToAcquirerData",
        "structured_sale_to_acquirer_data" to "Decoded fields sent inside PaymentRequest.SaleData.SaleToAcquirerData",
        "decode" to "Decode",
        "base64_decode_failed" to "Base64 value could not be decoded as JSON.",
        "readable_response" to "Readable response",
        "category" to "Category",
        "result" to "Result",
        "transaction_id" to "Transaction ID",
        "error_condition" to "Error condition",
        "additional_response_raw" to "AdditionalResponse raw",
        "decoded" to "Decoded",
        "diagnostics_body" to "Redacted operational state for the selected profile.",
        "show_latest_action_on_top" to "Show latest action on top",
        "none" to "none",
        "payments_app_api" to "Payments App API",
        "loaded_instances" to "Loaded instances",
        "transaction_history" to "Transaction history",
        "latest_service_id" to "Latest ServiceID",
        "latest_summary" to "Latest summary",
        "language_title" to "App language",
        "language_body" to "Choose how TapToPlay speaks on this device. The setting is saved locally.",
        "language_current" to "Current language",
        "language_option_selected" to "Selected",
        "about_message" to "Made by Javier de No, with help from Codex and GPT-5.5, for the team 💚🚀",
        "not_set" to "not set",
        "secret_set_hidden" to "set (hidden)",
        "item_count_one" to "1 item",
        "item_count_many" to "%d items",
        "loaded_instance_one" to "Loaded 1 Payments App instance.",
        "loaded_instance_many" to "Loaded %d Payments App instances.",
        "status_ready" to "Ready for boutique checkout",
        "status_language_changed" to "Language switched to %s.",
        "status_qr_rejected" to "QR rejected: %s",
        "status_sale_to_acquirer_loaded" to "SaleToAcquirerData QR loaded: %s.",
        "status_sale_to_acquirer_rejected" to "SaleToAcquirerData QR rejected: %s",
        "status_sale_to_acquirer_updated" to "SaleToAcquirerData updated from the field editor.",
        "status_favorite_saved" to "Saved %s as a SaleToAcquirerData favorite.",
        "status_favorite_applied" to "SaleToAcquirerData favorite applied: %s.",
        "status_favorite_removed" to "Removed SaleToAcquirerData favorite: %s.",
        "status_sale_to_acquirer_reset" to "SaleToAcquirerData reset to retail demo defaults.",
        "status_transactions_cleared" to "Transaction history cleared.",
        "status_active_profile_switched" to "Active profile switched deliberately.",
        "scan_profile_prompt" to "Scan a TapToPlay Adyen profile QR",
        "scan_sale_to_acquirer_prompt" to "Scan a SaleToAcquirerData JSON QR",
        "status_profile_active_updated" to "Scanned %s. Active profile updated.",
        "status_resolving_store" to "Resolving Adyen store name for %s...",
        "status_store_not_found" to "Scanned %s. Store %s was not found under %s.",
        "status_store_resolved" to "Scanned %s. Store name resolved from Adyen.",
        "status_store_lookup_failed" to "Scanned %s. Store name lookup failed: %s",
        "status_check_boarding_first" to "Check boarding first so Adyen can return a boarding request token.",
        "status_requesting_boarding_token" to "Requesting Adyen boarding token...",
        "status_opening_finish_boarding" to "Opening Adyen to finish boarding...",
        "status_boarding_token_failed" to "Boarding token failed: %s",
        "status_profile_removed" to "Removed %s and cleared its local boarding state.",
        "status_payments_instances_not_loaded" to "Payments App instances not loaded",
        "status_refreshing_payments_instances" to "Refreshing Payments App instances...",
        "status_no_payments_instances" to "No Payments App instances returned for this profile.",
        "status_payments_lookup_failed" to "Payments App lookup failed: %s",
        "status_revoking_instance" to "Revoking Payments App instance %s...",
        "status_revoked_instance" to "Revoked Payments App instance %s.",
        "status_revoke_failed" to "Revoke failed: %s",
        "status_payments_app_missing" to "Adyen Payments app for %s is not installed. Open Google Play from the setup block.",
        "status_opening_google_play" to "Opening Google Play for the %s Adyen Payments app.",
        "status_no_browser_google_play" to "No browser or Play Store app is available to open the %s download link.",
        "status_no_browser_qr_docs" to "No browser is available to open the QR documentation.",
        "status_need_installation_id" to "Check boarding first. Payments require an installation ID as POIID.",
        "status_opening_payment_app" to "Opening Adyen payment app with encrypted Terminal API request...",
        "status_refund_missing_transaction" to "Cannot refund yet: the Adyen transaction identifier is missing.",
        "status_refund_missing_profile" to "Cannot refund: select the Adyen profile used for the original payment.",
        "status_refund_missing_installation" to "Cannot refund: no installation ID is available for the Payments app.",
        "status_opening_refund" to "Opening Adyen with a referenced refund request...",
        "status_adyen_boarded_ready" to "Adyen app is boarded and ready.",
        "status_boarding_request_received" to "Boarding request token received. Tap Board to finish setup.",
        "status_boarding_error" to "Boarding error: %s",
        "status_adyen_not_boarded" to "Adyen app is not boarded yet.",
        "summary_approved" to "Approved%s",
        "summary_refused" to "Refused%s",
        "summary_failed" to "Failed | %s",
        "summary_boarding_response" to "Boarding response",
        "failure_refused_without_reason" to "Adyen refused the payment without a reason."
    ),
    productNames = mapOf(
        "linen-blazer" to "Linen Atelier Blazer",
        "silk-shirt" to "Washed Silk Shirt",
        "tailored-trouser" to "Tapered Wool Trouser",
        "cotton-dress" to "Poplin Midi Dress",
        "knit-cardigan" to "Merino Rib Cardigan",
        "leather-tote" to "Soft Market Tote",
    ),
    productDescriptions = mapOf(
        "linen-blazer" to "Relaxed tailoring in stone-washed linen with corozo buttons.",
        "silk-shirt" to "Fluid ivory silk with a softly structured collar.",
        "tailored-trouser" to "Clean front trouser with a cropped taper and satin waistband.",
        "cotton-dress" to "Crisp cotton poplin, deep pockets, and an architectural waist.",
        "knit-cardigan" to "Fine-gauge merino with horn buttons and a close rib finish.",
        "leather-tote" to "Unlined grained leather tote sized for shop floor essentials.",
    ),
    categories = mapOf(
        "All" to "All",
        "Outerwear" to "Outerwear",
        "Shirts" to "Shirts",
        "Trousers" to "Trousers",
        "Dresses" to "Dresses",
        "Knitwear" to "Knitwear",
        "Accessories" to "Accessories",
    ),
)

private val spanishStrings = TapToPlayStrings(
    language = AppLanguage.Spanish,
    values = englishStringsValues(
        "screen_catalog" to "Catalogo",
        "screen_checkout" to "Caja",
        "screen_payments_app" to "Payments App",
        "screen_transactions" to "Transacciones",
        "screen_diagnostics" to "Diagnostico",
        "screen_language" to "Idioma",
        "screen_about" to "About",
        "menu" to "Menu",
        "open_menu" to "Abrir menu",
        "scroll_to_cart" to "Ir al carrito",
        "latest_action" to "Ultima accion",
        "cart" to "Carrito",
        "cart_empty_hint" to "Anade prendas para preparar el cobro.",
        "cart_item_ready_one" to "1 articulo listo",
        "cart_item_ready_many" to "%d articulos listos",
        "go_to_checkout" to "Ir a caja",
        "no_payment_profile_selected" to "No hay perfil de pago seleccionado",
        "charging_profile" to "Perfil de cobro: %s (%s)",
        "added" to "Anadido",
        "add_to_cart" to "Anadir al carrito",
        "checkout_empty_hint" to "Anade prendas para iniciar un cobro Tap to Pay.",
        "clear" to "Vaciar",
        "total" to "Total",
        "reset" to "Restablecer",
        "scan_data_qr" to "Escanear QR de datos",
        "view" to "Ver",
        "hide" to "Ocultar",
        "save" to "Guardar",
        "apply" to "Aplicar",
        "close" to "Cerrar",
        "favorites" to "Favoritos",
        "use" to "Usar",
        "remove" to "Eliminar",
        "json_field_count_one" to "1 campo JSON",
        "json_field_count_many" to "%d campos JSON",
        "charge_live_payment" to "Cobrar pago real",
        "charge_test_payment" to "Cobrar pago de prueba",
        "payments_app_not_boarded" to "Payments App sin boarding",
        "payments_app_not_boarded_body" to "Abre el estado de Payments App para revisar el boarding, obtener un token de solicitud o terminar la configuracion antes de cobrar.",
        "open_payments_app_status" to "Abrir estado de Payments App",
        "confirm_live_payment" to "Confirmar pago real",
        "confirm_live_payment_body" to "Esto lanzara un cobro real de Adyen Tap to Pay.",
        "charge_live" to "Cobrar real",
        "cancel" to "Cancelar",
        "amount" to "Importe",
        "items" to "Articulos",
        "profile" to "Perfil",
        "environment" to "Entorno",
        "merchant" to "Merchant",
        "store_name" to "Nombre de tienda",
        "store" to "Tienda",
        "store_id" to "ID de tienda",
        "environment_test" to "pruebas",
        "environment_live" to "produccion",
        "payment_profile" to "Perfil de pago",
        "boarding_no_profile" to "Sin perfil",
        "boarding_boarded" to "Con boarding",
        "boarding_ready_to_board" to "Listo para boarding",
        "boarding_collapsed_setup" to "Setup contraido",
        "setup" to "Setup",
        "scan_qr" to "Escanear QR",
        "no_credential_profile_loaded" to "No hay perfil de credenciales cargado",
        "credential_profile_empty_body" to "Crea un QR de credenciales con el esquema de TapToPlay antes de hacer boarding de Adyen Payments app.",
        "open_qr_documentation" to "Abrir documentacion QR",
        "secure_device_vault" to "Boveda segura del dispositivo",
        "secure_device_vault_body" to "Los perfiles QR escaneados se guardan con preferencias cifradas de Android. Los secretos se muestran enmascarados.",
        "api_key" to "API key",
        "terminal_key" to "Clave de terminal",
        "passphrase" to "Passphrase",
        "installation" to "Instalacion",
        "boarding_request_token" to "Token de solicitud de boarding",
        "boarding_token" to "Token de boarding",
        "installation_not_returned_yet" to "aun no devuelta",
        "boarding_token_exchanged" to "canjeado por token de boarding",
        "boarding_token_received" to "recibido desde Check",
        "boarding_token_not_needed" to "no necesario tras boarding",
        "boarding_token_not_received" to "no recibido",
        "boarding_token_generated" to "generado para el ultimo enlace de Board",
        "boarding_token_not_generated" to "aun no generado",
        "boarding_token_not_requested" to "no solicitado",
        "check" to "Check",
        "board" to "Board",
        "reboard" to "Reboard",
        "remove_payment_profile_title" to "Eliminar perfil de pago?",
        "remove_payment_profile_body" to "Esto elimina %s de la boveda cifrada local y limpia su estado de boarding guardado. La autenticacion de la app de Adyen no se revoca salvo que revoques la instancia aparte.",
        "payments_app_not_installed" to "Payments app no instalada",
        "payments_app_not_installed_body" to "Instala la Adyen Payments app de %s desde Google Play, vuelve aqui y ejecuta Check otra vez.",
        "open_google_play" to "Abrir Google Play",
        "payments_app_instances" to "Instancias de Payments App",
        "payments_app_status_boarding" to "en boarding",
        "payments_app_status_boarded" to "con boarding",
        "payments_app_status_revoked" to "revocada",
        "payments_app_status_unknown" to "desconocida",
        "refresh" to "Actualizar",
        "hide_revoked" to "Ocultar revocadas",
        "show_revoked" to "Mostrar revocadas",
        "instances_no_profile" to "Escanea o selecciona un perfil de Adyen para inspeccionar instancias.",
        "instances_empty" to "Aun no hay instancias cargadas. Actualizar usa la API key del perfil escaneado.",
        "instances_only_revoked_hidden" to "Solo hay instancias revocadas ocultas. Muestralas para inspeccionarlas.",
        "current" to "Actual",
        "no_merchant_store_returned" to "Sin merchant/tienda devueltos",
        "revoke_instance" to "Revocar instancia",
        "revoke" to "Revocar",
        "revoke_instance_title" to "Revocar instancia de Payments App?",
        "revoke_instance_body" to "Esto revoca la instalacion %s en Adyen. Los pagos en esa app/dispositivo necesitaran reboarding despues.",
        "edit" to "Editar",
        "value" to "Valor",
        "remove_group" to "Eliminar grupo",
        "field_count_one" to "1 campo",
        "field_count_many" to "%d campos",
        "array_item_count_one" to "1 elemento",
        "array_item_count_many" to "%d elementos",
        "transactions_empty_title" to "Aun no hay intentos de pago",
        "saved_attempt_one" to "1 intento de pago guardado",
        "saved_attempt_many" to "%d intentos de pago guardados",
        "transactions_empty_body" to "Cada intento de cobro aparecera aqui con su solicitud Terminal API y la respuesta de Adyen.",
        "inspect" to "Inspeccionar",
        "adyen_issue" to "Incidencia de Adyen: %s",
        "transaction_status_pending" to "Pendiente",
        "transaction_status_approved" to "Aprobado",
        "transaction_status_refused" to "Rechazado",
        "transaction_status_failed" to "Fallido",
        "transaction_status_refunding" to "Reembolsando",
        "transaction_status_refunded" to "Reembolsado",
        "boarding_returned" to "Boarding devuelto",
        "refund_approved" to "Reembolso aprobado",
        "payment_approved" to "Pago aprobado",
        "payment_refused" to "Pago rechazado",
        "adyen_result" to "Resultado de Adyen",
        "done" to "Listo",
        "adyen_app_is_state" to "La app de Adyen esta %s. Installation ID: %s",
        "boarded" to "con boarding",
        "not_boarded" to "sin boarding",
        "not_supplied" to "no enviado",
        "previous_merchant" to "Merchant anterior: %s",
        "previous_store" to "Tienda anterior: %s",
        "reboarding_flow_started" to "Flujo de reboarding iniciado",
        "reference" to "Referencia: %s",
        "no_refusal_reason" to "No se envio motivo de rechazo.",
        "transaction" to "Transaccion",
        "refund" to "Reembolsar",
        "request" to "Solicitud",
        "response" to "Respuesta",
        "receipt" to "Recibo",
        "terminal_api_request" to "Solicitud Terminal API",
        "raw_terminal_api_request" to "Solicitud Terminal API sin procesar",
        "show_raw_json" to "Mostrar JSON sin procesar",
        "hide_raw_json" to "Ocultar JSON sin procesar",
        "json_parse_failed" to "No se pudo interpretar el JSON.",
        "important_response_fields" to "Campos importantes de respuesta",
        "adyen_failure_detail" to "Detalle de fallo de Adyen",
        "adyen_response" to "Respuesta de Adyen",
        "no_response_received" to "Aun no se ha recibido respuesta.",
        "raw_terminal_api_response" to "Respuesta Terminal API sin procesar",
        "raw_return_uri" to "URI de retorno sin procesar",
        "no_receipt_data" to "No se devolvio PaymentReceipt para esta transaccion.",
        "adyen_generated_receipt_data" to "Datos de recibo generados por Adyen",
        "signature" to "Firma",
        "receipt_status_voided" to "Anulado",
        "merchant_receipt" to "Recibo de comercio",
        "customer_receipt" to "Recibo de cliente",
        "receipt_type" to "Tipo",
        "receipt_payment_method" to "Metodo de pago",
        "receipt_card" to "Tarjeta",
        "receipt_card_number" to "Numero de tarjeta",
        "receipt_authorisation" to "Autorizacion",
        "receipt_date" to "Fecha",
        "receipt_time" to "Hora",
        "receipt_transaction_reference" to "Referencia de transaccion",
        "receipt_terminal" to "Terminal",
        "receipt_merchant_id" to "Merchant ID",
        "receipt_original_amount" to "Importe original",
        "receipt_shopper_amount" to "Importe del cliente",
        "receipt_tip_amount" to "Propina",
        "receipt_surcharge" to "Recargo",
        "receipt_cashback_amount" to "Cashback",
        "receipt_charity_amount" to "Donacion",
        "receipt_discount_amount" to "Descuento",
        "receipt_payment_method_variant" to "Variante de pago",
        "receipt_funding_source" to "Fuente de fondos",
        "receipt_product_type" to "Tipo de producto",
        "receipt_pos_entry_mode" to "Modo de entrada",
        "receipt_application" to "Aplicacion",
        "receipt_expiry_date" to "Caducidad",
        "receipt_cardholder_name" to "Titular",
        "receipt_account_type" to "Tipo de cuenta",
        "receipt_authorization_type" to "Tipo de autorizacion",
        "receipt_authorization_response" to "Respuesta de autorizacion",
        "receipt_cvm_result" to "Resultado CVM",
        "receipt_additional_emv_data" to "Datos EMV adicionales",
        "receipt_pan_sequence" to "Secuencia PAN",
        "receipt_current_balance" to "Saldo actual",
        "receipt_dcc_explanation" to "Explicacion DCC",
        "receipt_dcc_markup" to "Margen DCC",
        "receipt_dcc_rate" to "Tasa DCC",
        "receipt_dcc_shopper_amount" to "Importe DCC cliente",
        "receipt_dcc_source" to "Fuente DCC",
        "receipt_wallet_dcc_amount" to "Importe DCC wallet",
        "receipt_wallet_dcc_rate" to "Tasa DCC wallet",
        "receipt_wallet_operation" to "Operacion wallet",
        "receipt_wallet_reference" to "Referencia wallet",
        "receipt_token_variant" to "Variante de token",
        "receipt_buyer_id" to "Buyer ID",
        "receipt_qr_code" to "Codigo QR",
        "request_summary" to "Resumen de solicitud",
        "message_category" to "Categoria de mensaje",
        "service_id" to "ServiceID",
        "sale_transaction" to "Transaccion de venta",
        "adyen_transaction" to "Transaccion Adyen",
        "refund_of" to "Reembolso de",
        "decoded_sale_to_acquirer_data" to "SaleToAcquirerData decodificado",
        "no_sale_to_acquirer_data" to "Esta solicitud no incluye PaymentRequest.SaleData.SaleToAcquirerData.",
        "raw_sale_to_acquirer_data" to "JSON enviado dentro de PaymentRequest.SaleData.SaleToAcquirerData",
        "structured_sale_to_acquirer_data" to "Campos decodificados enviados dentro de PaymentRequest.SaleData.SaleToAcquirerData",
        "decode" to "Decodificar",
        "base64_decode_failed" to "El valor Base64 no se pudo decodificar como JSON.",
        "readable_response" to "Respuesta legible",
        "category" to "Categoria",
        "result" to "Resultado",
        "transaction_id" to "ID de transaccion",
        "error_condition" to "Condicion de error",
        "additional_response_raw" to "AdditionalResponse sin procesar",
        "decoded" to "Decodificado",
        "diagnostics_body" to "Estado operativo redactado para el perfil seleccionado.",
        "show_latest_action_on_top" to "Mostrar ultima accion arriba",
        "none" to "ninguno",
        "payments_app_api" to "API de Payments App",
        "loaded_instances" to "Instancias cargadas",
        "transaction_history" to "Historial de transacciones",
        "latest_service_id" to "Ultimo ServiceID",
        "latest_summary" to "Ultimo resumen",
        "language_title" to "Idioma de la app",
        "language_body" to "Elige como habla TapToPlay en este dispositivo. El ajuste se guarda localmente.",
        "language_current" to "Idioma actual",
        "language_option_selected" to "Seleccionado",
        "about_message" to "Hecho por Javier de No, con ayuda de Codex y GPT-5.5, para el equipo 💚🚀",
        "not_set" to "sin configurar",
        "secret_set_hidden" to "configurado (oculto)",
        "item_count_one" to "1 articulo",
        "item_count_many" to "%d articulos",
        "loaded_instance_one" to "Cargada 1 instancia de Payments App.",
        "loaded_instance_many" to "Cargadas %d instancias de Payments App.",
        "status_ready" to "Listo para caja boutique",
        "status_language_changed" to "Idioma cambiado a %s.",
        "status_qr_rejected" to "QR rechazado: %s",
        "status_sale_to_acquirer_loaded" to "QR SaleToAcquirerData cargado: %s.",
        "status_sale_to_acquirer_rejected" to "QR SaleToAcquirerData rechazado: %s",
        "status_sale_to_acquirer_updated" to "SaleToAcquirerData actualizado desde el editor de campos.",
        "status_favorite_saved" to "%s guardado como favorito de SaleToAcquirerData.",
        "status_favorite_applied" to "Favorito SaleToAcquirerData aplicado: %s.",
        "status_favorite_removed" to "Favorito SaleToAcquirerData eliminado: %s.",
        "status_sale_to_acquirer_reset" to "SaleToAcquirerData restablecido a los valores demo retail.",
        "status_transactions_cleared" to "Historial de transacciones vaciado.",
        "status_active_profile_switched" to "Perfil activo cambiado deliberadamente.",
        "scan_profile_prompt" to "Escanea un QR de perfil Adyen de TapToPlay",
        "scan_sale_to_acquirer_prompt" to "Escanea un QR JSON de SaleToAcquirerData",
        "status_profile_active_updated" to "%s escaneado. Perfil activo actualizado.",
        "status_resolving_store" to "Resolviendo el nombre de tienda Adyen para %s...",
        "status_store_not_found" to "%s escaneado. La tienda %s no se encontro bajo %s.",
        "status_store_resolved" to "%s escaneado. Nombre de tienda resuelto desde Adyen.",
        "status_store_lookup_failed" to "%s escaneado. Fallo al buscar nombre de tienda: %s",
        "status_check_boarding_first" to "Haz Check primero para que Adyen pueda devolver un token de solicitud de boarding.",
        "status_requesting_boarding_token" to "Solicitando token de boarding a Adyen...",
        "status_opening_finish_boarding" to "Abriendo Adyen para terminar el boarding...",
        "status_boarding_token_failed" to "Fallo de token de boarding: %s",
        "status_profile_removed" to "%s eliminado y su estado local de boarding limpiado.",
        "status_payments_instances_not_loaded" to "Instancias de Payments App no cargadas",
        "status_refreshing_payments_instances" to "Actualizando instancias de Payments App...",
        "status_no_payments_instances" to "Adyen no devolvio instancias de Payments App para este perfil.",
        "status_payments_lookup_failed" to "Fallo al consultar Payments App: %s",
        "status_revoking_instance" to "Revocando instancia de Payments App %s...",
        "status_revoked_instance" to "Instancia de Payments App %s revocada.",
        "status_revoke_failed" to "Fallo al revocar: %s",
        "status_payments_app_missing" to "La Adyen Payments app de %s no esta instalada. Abre Google Play desde el bloque de setup.",
        "status_opening_google_play" to "Abriendo Google Play para la Adyen Payments app de %s.",
        "status_no_browser_google_play" to "No hay navegador o Play Store disponible para abrir el enlace de descarga de %s.",
        "status_no_browser_qr_docs" to "No hay navegador disponible para abrir la documentacion QR.",
        "status_need_installation_id" to "Haz Check primero. Los pagos requieren un installation ID como POIID.",
        "status_opening_payment_app" to "Abriendo Adyen payment app con solicitud Terminal API cifrada...",
        "status_refund_missing_transaction" to "Aun no se puede reembolsar: falta el identificador de transaccion Adyen.",
        "status_refund_missing_profile" to "No se puede reembolsar: selecciona el perfil de Adyen usado en el pago original.",
        "status_refund_missing_installation" to "No se puede reembolsar: no hay installation ID disponible para Payments app.",
        "status_opening_refund" to "Abriendo Adyen con una solicitud de reembolso referenciado...",
        "status_adyen_boarded_ready" to "La app de Adyen tiene boarding y esta lista.",
        "status_boarding_request_received" to "Token de solicitud de boarding recibido. Toca Board para terminar el setup.",
        "status_boarding_error" to "Error de boarding: %s",
        "status_adyen_not_boarded" to "La app de Adyen aun no tiene boarding.",
        "summary_approved" to "Aprobado%s",
        "summary_refused" to "Rechazado%s",
        "summary_failed" to "Fallido | %s",
        "summary_boarding_response" to "Respuesta de boarding",
        "failure_refused_without_reason" to "Adyen rechazo el pago sin indicar motivo."
    ),
    productNames = mapOf(
        "linen-blazer" to "Blazer Atelier de lino",
        "silk-shirt" to "Camisa de seda lavada",
        "tailored-trouser" to "Pantalon de lana tapered",
        "cotton-dress" to "Vestido midi de popelin",
        "knit-cardigan" to "Cardigan de merino canalé",
        "leather-tote" to "Bolso market de piel suave",
    ),
    productDescriptions = mapOf(
        "linen-blazer" to "Sastreria relajada en lino lavado a la piedra con botones de corozo.",
        "silk-shirt" to "Seda marfil fluida con cuello suavemente estructurado.",
        "tailored-trouser" to "Pantalon limpio con corte cropped, bajo tapered y cintura satinada.",
        "cotton-dress" to "Popelin de algodon crujiente, bolsillos profundos y cintura arquitectonica.",
        "knit-cardigan" to "Merino fino con botones de asta y acabado acanalado ajustado.",
        "leather-tote" to "Tote de piel granulada sin forro, pensado para esenciales de tienda.",
    ),
    categories = mapOf(
        "All" to "Todo",
        "Outerwear" to "Abrigos",
        "Shirts" to "Camisas",
        "Trousers" to "Pantalones",
        "Dresses" to "Vestidos",
        "Knitwear" to "Punto",
        "Accessories" to "Accesorios",
    ),
)

private val dutchStrings = TapToPlayStrings(
    language = AppLanguage.Dutch,
    values = englishStringsValues(
        "screen_catalog" to "Catalogus",
        "screen_checkout" to "Afrekenen",
        "screen_payments_app" to "Payments App",
        "screen_transactions" to "Transacties",
        "screen_diagnostics" to "Diagnose",
        "screen_language" to "Taal",
        "screen_about" to "About",
        "menu" to "Menu",
        "open_menu" to "Menu openen",
        "scroll_to_cart" to "Naar winkelmand",
        "latest_action" to "Laatste actie",
        "cart" to "Winkelmand",
        "cart_empty_hint" to "Voeg items toe om een checkout te starten.",
        "cart_item_ready_one" to "1 item klaar",
        "cart_item_ready_many" to "%d items klaar",
        "go_to_checkout" to "Naar afrekenen",
        "no_payment_profile_selected" to "Geen betaalprofiel geselecteerd",
        "charging_profile" to "Betaalprofiel: %s (%s)",
        "added" to "Toegevoegd",
        "add_to_cart" to "Toevoegen",
        "checkout_empty_hint" to "Voeg items toe om een Tap to Pay-betaling te starten.",
        "clear" to "Wissen",
        "total" to "Totaal",
        "reset" to "Resetten",
        "scan_data_qr" to "Data-QR scannen",
        "view" to "Bekijken",
        "hide" to "Verbergen",
        "save" to "Opslaan",
        "apply" to "Toepassen",
        "close" to "Sluiten",
        "favorites" to "Favorieten",
        "use" to "Gebruiken",
        "remove" to "Verwijderen",
        "json_field_count_one" to "1 JSON-veld",
        "json_field_count_many" to "%d JSON-velden",
        "charge_live_payment" to "Live betaling starten",
        "charge_test_payment" to "Testbetaling starten",
        "payments_app_not_boarded" to "Payment App niet geboard",
        "payments_app_not_boarded_body" to "Open de Payments App-status om boarding te controleren, een request token te krijgen of setup af te ronden voordat je betaalt.",
        "open_payments_app_status" to "Payments App-status openen",
        "confirm_live_payment" to "Live betaling bevestigen",
        "confirm_live_payment_body" to "Dit start een live Adyen Tap to Pay-betaling.",
        "charge_live" to "Live betalen",
        "cancel" to "Annuleren",
        "amount" to "Bedrag",
        "items" to "Items",
        "profile" to "Profiel",
        "environment" to "Omgeving",
        "merchant" to "Merchant",
        "store_name" to "Winkelnaam",
        "store" to "Winkel",
        "store_id" to "Winkel-ID",
        "environment_test" to "test",
        "environment_live" to "live",
        "payment_profile" to "Betaalprofiel",
        "boarding_no_profile" to "Geen profiel",
        "boarding_boarded" to "Geboard",
        "boarding_ready_to_board" to "Klaar voor boarding",
        "boarding_collapsed_setup" to "Setup ingeklapt",
        "setup" to "Setup",
        "scan_qr" to "QR scannen",
        "no_credential_profile_loaded" to "Geen credentialprofiel geladen",
        "credential_profile_empty_body" to "Maak een credential-QR met het TapToPlay-schema voordat je de Adyen Payments app boardt.",
        "open_qr_documentation" to "QR-documentatie openen",
        "secure_device_vault" to "Veilige kluis op apparaat",
        "secure_device_vault_body" to "Gescande QR-profielen worden opgeslagen met Android encrypted preferences. Geheimen blijven gemaskeerd in de app.",
        "api_key" to "API key",
        "terminal_key" to "Terminal key",
        "passphrase" to "Passphrase",
        "installation" to "Installatie",
        "boarding_request_token" to "Boarding request token",
        "boarding_token" to "Boarding token",
        "installation_not_returned_yet" to "nog niet ontvangen",
        "boarding_token_exchanged" to "omgewisseld voor boarding token",
        "boarding_token_received" to "ontvangen via Check",
        "boarding_token_not_needed" to "niet nodig na boarding",
        "boarding_token_not_received" to "niet ontvangen",
        "boarding_token_generated" to "gegenereerd voor de laatste Board-link",
        "boarding_token_not_generated" to "nog niet gegenereerd",
        "boarding_token_not_requested" to "niet aangevraagd",
        "check" to "Check",
        "board" to "Board",
        "reboard" to "Reboard",
        "remove_payment_profile_title" to "Betaalprofiel verwijderen?",
        "remove_payment_profile_body" to "Dit verwijdert %s uit de lokale versleutelde kluis en wist de opgeslagen boardingstatus. Authenticatie in de Adyen-app wordt pas ingetrokken als je de instantie apart revoke't.",
        "payments_app_not_installed" to "Payments app niet geinstalleerd",
        "payments_app_not_installed_body" to "Installeer de %s Adyen Payments app via Google Play, kom terug en voer Check opnieuw uit.",
        "open_google_play" to "Google Play openen",
        "payments_app_instances" to "Payments App-instanties",
        "payments_app_status_boarding" to "boarding",
        "payments_app_status_boarded" to "geboard",
        "payments_app_status_revoked" to "ingetrokken",
        "payments_app_status_unknown" to "onbekend",
        "refresh" to "Vernieuwen",
        "hide_revoked" to "Ingetrokken verbergen",
        "show_revoked" to "Ingetrokken tonen",
        "instances_no_profile" to "Scan of selecteer een Adyen-profiel om app-instanties te bekijken.",
        "instances_empty" to "Er zijn nog geen instanties geladen. Vernieuwen gebruikt de API key van het gescande profiel.",
        "instances_only_revoked_hidden" to "Alleen ingetrokken instanties zijn verborgen. Toon ze om ze te inspecteren.",
        "current" to "Huidig",
        "no_merchant_store_returned" to "Geen merchant/winkel ontvangen",
        "revoke_instance" to "Instantie intrekken",
        "revoke" to "Intrekken",
        "revoke_instance_title" to "Payments App-instantie intrekken?",
        "revoke_instance_body" to "Dit trekt installatie %s in via Adyen. Betalingen op die app of dat apparaat hebben daarna reboarding nodig.",
        "edit" to "Bewerken",
        "value" to "Waarde",
        "remove_group" to "Groep verwijderen",
        "field_count_one" to "1 veld",
        "field_count_many" to "%d velden",
        "array_item_count_one" to "1 item",
        "array_item_count_many" to "%d items",
        "transactions_empty_title" to "Nog geen betaalpogingen",
        "saved_attempt_one" to "1 opgeslagen betaalpoging",
        "saved_attempt_many" to "%d opgeslagen betaalpogingen",
        "transactions_empty_body" to "Elke checkoutpoging verschijnt hier met de Terminal API-request en Adyen-response.",
        "inspect" to "Inspecteren",
        "adyen_issue" to "Adyen-probleem: %s",
        "transaction_status_pending" to "In afwachting",
        "transaction_status_approved" to "Goedgekeurd",
        "transaction_status_refused" to "Geweigerd",
        "transaction_status_failed" to "Mislukt",
        "transaction_status_refunding" to "Terugbetaling bezig",
        "transaction_status_refunded" to "Terugbetaald",
        "boarding_returned" to "Boarding teruggekeerd",
        "refund_approved" to "Terugbetaling goedgekeurd",
        "payment_approved" to "Betaling goedgekeurd",
        "payment_refused" to "Betaling geweigerd",
        "adyen_result" to "Adyen-resultaat",
        "done" to "Klaar",
        "adyen_app_is_state" to "De Adyen-app is %s. Installation ID: %s",
        "boarded" to "geboard",
        "not_boarded" to "niet geboard",
        "not_supplied" to "niet meegegeven",
        "previous_merchant" to "Vorige merchant: %s",
        "previous_store" to "Vorige winkel: %s",
        "reboarding_flow_started" to "Reboardingflow gestart",
        "reference" to "Referentie: %s",
        "no_refusal_reason" to "Geen weigeringsreden meegegeven.",
        "transaction" to "Transactie",
        "refund" to "Terugbetalen",
        "request" to "Request",
        "response" to "Response",
        "receipt" to "Bon",
        "terminal_api_request" to "Terminal API-request",
        "raw_terminal_api_request" to "Ruwe Terminal API-request",
        "show_raw_json" to "Ruwe JSON tonen",
        "hide_raw_json" to "Ruwe JSON verbergen",
        "json_parse_failed" to "JSON kon niet worden gelezen.",
        "important_response_fields" to "Belangrijke responsevelden",
        "adyen_failure_detail" to "Adyen-foutdetail",
        "adyen_response" to "Adyen-response",
        "no_response_received" to "Er is nog geen response ontvangen.",
        "raw_terminal_api_response" to "Ruwe Terminal API-response",
        "raw_return_uri" to "Ruwe return-URI",
        "no_receipt_data" to "Er is geen PaymentReceipt-data teruggegeven voor deze transactie.",
        "adyen_generated_receipt_data" to "Door Adyen gegenereerde bondata",
        "signature" to "Handtekening",
        "receipt_status_voided" to "Geannuleerd",
        "merchant_receipt" to "Merchantbon",
        "customer_receipt" to "Klantbon",
        "receipt_type" to "Type",
        "receipt_payment_method" to "Betaalmethode",
        "receipt_card" to "Kaart",
        "receipt_card_number" to "Kaartnummer",
        "receipt_authorisation" to "Autorisatie",
        "receipt_date" to "Datum",
        "receipt_time" to "Tijd",
        "receipt_transaction_reference" to "Transactiereferentie",
        "receipt_terminal" to "Terminal",
        "receipt_merchant_id" to "Merchant ID",
        "receipt_original_amount" to "Oorspronkelijk bedrag",
        "receipt_shopper_amount" to "Klantbedrag",
        "receipt_tip_amount" to "Fooi",
        "receipt_surcharge" to "Toeslag",
        "receipt_cashback_amount" to "Cashback",
        "receipt_charity_amount" to "Donatie",
        "receipt_discount_amount" to "Korting",
        "receipt_payment_method_variant" to "Betaalmethodevariant",
        "receipt_funding_source" to "Funding source",
        "receipt_product_type" to "Producttype",
        "receipt_pos_entry_mode" to "Invoermethode",
        "receipt_application" to "Applicatie",
        "receipt_expiry_date" to "Vervaldatum",
        "receipt_cardholder_name" to "Kaarthouder",
        "receipt_account_type" to "Rekeningtype",
        "receipt_authorization_type" to "Autorisatietype",
        "receipt_authorization_response" to "Autorisatierespons",
        "receipt_cvm_result" to "CVM-resultaat",
        "receipt_additional_emv_data" to "Aanvullende EMV-data",
        "receipt_pan_sequence" to "PAN-volgnummer",
        "receipt_current_balance" to "Huidig saldo",
        "receipt_dcc_explanation" to "DCC-uitleg",
        "receipt_dcc_markup" to "DCC-opslag",
        "receipt_dcc_rate" to "DCC-koers",
        "receipt_dcc_shopper_amount" to "DCC-klantbedrag",
        "receipt_dcc_source" to "DCC-bron",
        "receipt_wallet_dcc_amount" to "Wallet DCC-bedrag",
        "receipt_wallet_dcc_rate" to "Wallet DCC-koers",
        "receipt_wallet_operation" to "Wallet-operatie",
        "receipt_wallet_reference" to "Walletreferentie",
        "receipt_token_variant" to "Tokenvariant",
        "receipt_buyer_id" to "Buyer ID",
        "receipt_qr_code" to "QR-code",
        "request_summary" to "Requestsamenvatting",
        "message_category" to "Message category",
        "service_id" to "ServiceID",
        "sale_transaction" to "Sale transaction",
        "adyen_transaction" to "Adyen-transactie",
        "refund_of" to "Terugbetaling van",
        "decoded_sale_to_acquirer_data" to "Gedecodeerde SaleToAcquirerData",
        "no_sale_to_acquirer_data" to "Deze request bevat geen PaymentRequest.SaleData.SaleToAcquirerData.",
        "raw_sale_to_acquirer_data" to "Ruwe JSON binnen PaymentRequest.SaleData.SaleToAcquirerData",
        "structured_sale_to_acquirer_data" to "Gedecodeerde velden binnen PaymentRequest.SaleData.SaleToAcquirerData",
        "decode" to "Decoderen",
        "base64_decode_failed" to "De Base64-waarde kon niet als JSON worden gedecodeerd.",
        "readable_response" to "Leesbare response",
        "category" to "Categorie",
        "result" to "Resultaat",
        "transaction_id" to "Transactie-ID",
        "error_condition" to "Error condition",
        "additional_response_raw" to "AdditionalResponse ruw",
        "decoded" to "Gedecodeerd",
        "diagnostics_body" to "Geredigeerde operationele status voor het geselecteerde profiel.",
        "show_latest_action_on_top" to "Laatste actie bovenaan tonen",
        "none" to "geen",
        "payments_app_api" to "Payments App API",
        "loaded_instances" to "Geladen instanties",
        "transaction_history" to "Transactiegeschiedenis",
        "latest_service_id" to "Laatste ServiceID",
        "latest_summary" to "Laatste samenvatting",
        "language_title" to "App-taal",
        "language_body" to "Kies hoe TapToPlay op dit apparaat spreekt. De instelling wordt lokaal opgeslagen.",
        "language_current" to "Huidige taal",
        "language_option_selected" to "Geselecteerd",
        "about_message" to "Gemaakt door Javier de No, met hulp van Codex en GPT-5.5, voor het team 💚🚀",
        "not_set" to "niet ingesteld",
        "secret_set_hidden" to "ingesteld (verborgen)",
        "item_count_one" to "1 item",
        "item_count_many" to "%d items",
        "loaded_instance_one" to "1 Payments App-instantie geladen.",
        "loaded_instance_many" to "%d Payments App-instanties geladen.",
        "status_ready" to "Klaar voor boutique checkout",
        "status_language_changed" to "Taal gewijzigd naar %s.",
        "status_qr_rejected" to "QR geweigerd: %s",
        "status_sale_to_acquirer_loaded" to "SaleToAcquirerData-QR geladen: %s.",
        "status_sale_to_acquirer_rejected" to "SaleToAcquirerData-QR geweigerd: %s",
        "status_sale_to_acquirer_updated" to "SaleToAcquirerData bijgewerkt vanuit de veldeditor.",
        "status_favorite_saved" to "%s opgeslagen als SaleToAcquirerData-favoriet.",
        "status_favorite_applied" to "SaleToAcquirerData-favoriet toegepast: %s.",
        "status_favorite_removed" to "SaleToAcquirerData-favoriet verwijderd: %s.",
        "status_sale_to_acquirer_reset" to "SaleToAcquirerData teruggezet naar retaildemo-standaard.",
        "status_transactions_cleared" to "Transactiegeschiedenis gewist.",
        "status_active_profile_switched" to "Actief profiel bewust gewijzigd.",
        "scan_profile_prompt" to "Scan een TapToPlay Adyen-profiel-QR",
        "scan_sale_to_acquirer_prompt" to "Scan een SaleToAcquirerData JSON-QR",
        "status_profile_active_updated" to "%s gescand. Actief profiel bijgewerkt.",
        "status_resolving_store" to "Adyen-winkelnaam ophalen voor %s...",
        "status_store_not_found" to "%s gescand. Winkel %s is niet gevonden onder %s.",
        "status_store_resolved" to "%s gescand. Winkelnaam opgehaald uit Adyen.",
        "status_store_lookup_failed" to "%s gescand. Winkelnaam opzoeken mislukt: %s",
        "status_check_boarding_first" to "Voer eerst Check uit zodat Adyen een boarding request token kan teruggeven.",
        "status_requesting_boarding_token" to "Adyen boarding token aanvragen...",
        "status_opening_finish_boarding" to "Adyen openen om boarding af te ronden...",
        "status_boarding_token_failed" to "Boarding token mislukt: %s",
        "status_profile_removed" to "%s verwijderd en lokale boardingstatus gewist.",
        "status_payments_instances_not_loaded" to "Payments App-instanties niet geladen",
        "status_refreshing_payments_instances" to "Payments App-instanties vernieuwen...",
        "status_no_payments_instances" to "Geen Payments App-instanties teruggegeven voor dit profiel.",
        "status_payments_lookup_failed" to "Payments App-opzoekactie mislukt: %s",
        "status_revoking_instance" to "Payments App-instantie %s intrekken...",
        "status_revoked_instance" to "Payments App-instantie %s ingetrokken.",
        "status_revoke_failed" to "Intrekken mislukt: %s",
        "status_payments_app_missing" to "De Adyen Payments app voor %s is niet geinstalleerd. Open Google Play vanuit het setupblok.",
        "status_opening_google_play" to "Google Play openen voor de %s Adyen Payments app.",
        "status_no_browser_google_play" to "Geen browser of Play Store-app beschikbaar om de %s-downloadlink te openen.",
        "status_no_browser_qr_docs" to "Geen browser beschikbaar om de QR-documentatie te openen.",
        "status_need_installation_id" to "Voer eerst Check uit. Betalingen vereisen een installation ID als POIID.",
        "status_opening_payment_app" to "Adyen payment app openen met versleutelde Terminal API-request...",
        "status_refund_missing_transaction" to "Kan nog niet terugbetalen: de Adyen-transactie-ID ontbreekt.",
        "status_refund_missing_profile" to "Kan niet terugbetalen: selecteer het Adyen-profiel van de oorspronkelijke betaling.",
        "status_refund_missing_installation" to "Kan niet terugbetalen: er is geen installation ID beschikbaar voor de Payments app.",
        "status_opening_refund" to "Adyen openen met een referenced refund-request...",
        "status_adyen_boarded_ready" to "De Adyen-app is geboard en klaar.",
        "status_boarding_request_received" to "Boarding request token ontvangen. Tik op Board om setup af te ronden.",
        "status_boarding_error" to "Boardingfout: %s",
        "status_adyen_not_boarded" to "De Adyen-app is nog niet geboard.",
        "summary_approved" to "Goedgekeurd%s",
        "summary_refused" to "Geweigerd%s",
        "summary_failed" to "Mislukt | %s",
        "summary_boarding_response" to "Boardingresponse",
        "failure_refused_without_reason" to "Adyen heeft de betaling geweigerd zonder reden."
    ),
    productNames = mapOf(
        "linen-blazer" to "Linnen atelierblazer",
        "silk-shirt" to "Gewassen zijden overhemd",
        "tailored-trouser" to "Taps toelopende wollen broek",
        "cotton-dress" to "Poplin midi-jurk",
        "knit-cardigan" to "Merino ribvest",
        "leather-tote" to "Zachte market tote",
    ),
    productDescriptions = mapOf(
        "linen-blazer" to "Ontspannen tailoring in stone-washed linnen met corozo-knopen.",
        "silk-shirt" to "Vloeiende ivoorkleurige zijde met een zacht gestructureerde kraag.",
        "tailored-trouser" to "Strakke pantalon met cropped taper en satijnen tailleband.",
        "cotton-dress" to "Crisp katoenen poplin, diepe zakken en een architectonische taille.",
        "knit-cardigan" to "Fijngebreide merino met hoornknopen en een aansluitende ribafwerking.",
        "leather-tote" to "Ongevoerde tote van generfd leer, formaat voor winkelvloerbenodigdheden.",
    ),
    categories = mapOf(
        "All" to "Alles",
        "Outerwear" to "Outerwear",
        "Shirts" to "Shirts",
        "Trousers" to "Broeken",
        "Dresses" to "Jurken",
        "Knitwear" to "Knitwear",
        "Accessories" to "Accessoires",
    ),
)

private fun englishStringsValues(vararg overrides: Pair<String, String>): Map<String, String> =
    englishStrings.values + overrides
